### ISSUE TITLE
Exception on Flutter Web

### ISSUE THREAD

**Issue by apgapg** [tusharojha/web_scraper#6] opened 2020-06-24 13:59 UTC
Using v0.0.6 
Web scrapper gives exception on running flutter web

```
Error: Instance of 'WebScraperException'
    at Object.throw_ [as throw] (http://localhost:42637/dart_sdk.js:4464:11)
    at web_scraper.WebScraper.new.loadWebPage (http://localhost:42637/packages/web_scraper/web_scraper.dart.lib.js:68:23)
    at loadWebPage.throw (<anonymous>)
    at http://localhost:42637/dart_sdk.js:37111:38
    at _RootZone.runBinary (http://localhost:42637/dart_sdk.js:36964:58)
    at _FutureListener.thenAwait.handleError (http://localhost:42637/dart_sdk.js:32058:48)
    at handleError (http://localhost:42637/dart_sdk.js:32609:51)
    at Function._propagateToListeners (http://localhost:42637/dart_sdk.js:32635:17)
    at _Future.new.[_completeError] (http://localhost:42637/dart_sdk.js:32482:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:42637/dart_sdk.js:32520:31)
    at Object._microtaskLoop (http://localhost:42637/dart_sdk.js:37220:13)
    at _startMicrotaskLoop (http://localhost:42637/dart_sdk.js:37226:13)
    at http://localhost:42637/dart_sdk.js:32848:9

```

**Comment by tusharojha** [comment] 2020-06-26 07:07
Hi @apgapg 
I think the problem is because the URL you are trying to scrap is not available. 
Please check the webpage.

**Comment by apgapg** [comment] 2020-06-26 08:44
It works on android device. Is it something CORS issue?

**Comment by tusharojha** [comment] 2020-06-30 12:28
Yes, It may be a CORS issue because I have tried myself and its working.
I suggest you try with some other website.

**Comment by apgapg** [comment] 2020-06-30 14:31
Image.network loads image from different domain. But cachednetworkimage unable to show image because of cors issue

**Comment by v-grabko1999** [comment] 2020-07-07 18:27
This library will work as expected (with any sites) only in the form of a native application. If you are compiling into a web view then watch out for the CORS headers. More details: [developer.mozilla.org/en/docs/Web/HTTP/CORS](https://developer.mozilla.org/en/docs/Web/HTTP/CORS)

**Comment by v-grabko1999** [comment] 2020-07-10 07:30
An example of a solution to your problem: https://github.com/gskinnerTeam/flokk#cors-proxy

**Comment by tusharojha** [comment] 2020-07-13 20:45
I hope this will help @apgapg 
I am closing this issue as of now, feel free to open again if you face any issue.

Thanks, @v-grabko1999

**Closed by tusharojha** 2020-07-13 20:45 UTC
