### ISSUE TITLE
Cant get data from div has 2 div child has same class name

### ISSUE THREAD

**Issue by izark99** [tusharojha/web_scraper#20] opened 2020-12-27 08:59 UTC
Cant get data from div has 2 div child has same class name
![image](https://user-images.githubusercontent.com/20470671/103167265-4e226480-485c-11eb-82a7-556fd2200549.png)

**Comment by tusharojha** [comment] 2020-12-27 09:11
Hi @izark99.
Thanks for filing an issue but can you please give a bit more information about the issue and any steps to reproduce the same.

**Comment by izark99** [comment] 2020-12-27 10:01
> Hi @izark99.
> Thanks for filing an issue but can you please give a bit more information about the issue and any steps to reproduce the same.

_tempList = webScraper.getElement(
        'div.wrapper > div.container > div.row > div.col-sm-8 > div.movie-rate > div.rate-star > div.movie-eps-all > div.movie-eps-wrapper > a.movie-eps-item',
        ['title', 'href'],
      );

In div.movie-eps-all has 2 div.movie-eps-wrapper. So when I run, _tempList is empty.

**Comment by tusharojha** [comment] 2021-01-07 11:33
Hi @izark99,
I tried to reproduce the issue and fortunately for me, it's working. Here are some checks/tips I would suggest you try:

- CHECK: Make sure it can reach the website (there should be no CORS issue or network issue)
- CHECK: The element you are looking for should be present at the specified address
- TIP: You don't need to pass the whole address from body to the element. You can just look-up to some simple and short address which can target the element(s). example: rather than passing this `div.wrapper > div.container > div.row > div.col-sm-8 > div.movie-rate > div.rate-star > div.movie-eps-all > div.movie-eps-wrapper > a.movie-eps-item`  you can just pass `.movie-eps-wrapper > .movie-eps-item` or even `.movie-eps-item`.

I would suggest trying again while keeping the above points in mind. As of now, I am closing the issue since It's not a bug related to the package. If you still face problems feel free to create a new discussion.

**Closed by tusharojha** 2021-01-07 11:33 UTC
